### ISSUE TITLE
Better Installation Instruction

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/docs#13]
After installing sphinx, whenever I try to transpile the docs to html I find that I get this error:

> Extension error:
> Could not import recommonmark.parser (needed for source parser) (exception: No module named recommonmark.parser)
> Makefile:20: recipe for target 'html' failed
> make: *** [html] Error 2

Would it be better for the installation instructions to recommend using a virtual environment and installing required packages from a requirements.txt file for doc development?

Example:
` pip install -r requirements.txt `

**Comment by dob** [comment]
Closed via #14
