### ISSUE TITLE
Update Welcome Intro page on docs

### ISSUE THREAD

**Issue by hnjolles1** [livepeer/docs#133]
Update "Intro" with a minimally robust Welcome page: 
- Sets the Livepeer's delightful tone -- engaging readers in the ease of use and benefit of working with the platform 
Provides a frame of reference so that:
- stakeholders can get a high-level understanding about the Livepeer offering
-  What's New -- release/migration highlights, e.g. L2, docs updates 
- set expectations about how the documentation can guide them 
- highlights paths/journeys stakeholders can follow with the support of the documentation 
so that they can
- participate according to their chosen interest/role-persona as:
Video Miners
Transcoders
Developers
and Token Holders and Delegators know how to get information on what they need to know
Contributors

**Comment by hthillman** [comment]
merged in https://github.com/livepeer/docs/pull/143
