### ISSUE TITLE
Getting Started Page

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/docs#15]
1. In the “Download Livepeer” section. You could probably say where might be the best place to put the files.
 
Example: 

- Download the proper package for your operating system to your downloads folder.
- Run the using the following commands:

2. In the “Rinkeby Testnet” section it might be helpful to put “livepeer -rinkeby” in a block that looks like it should be ran from the command line. This would differentiate it from the sentence and make it standout. Example:
In your terminal run:
``` $ livepeer -rinkeby ```

2. When using the test network, you may want to direct the user to documentation that will help them in the event rinkeby cannot issue ETH to their address. https://faucet.rinkeby.io/ kept saying “URL doesn't link to supported services”, when I try to get test ETH.

**Comment by bdiallo** [comment]
Hi I have the same error, have you found a solution
https://faucet.rinkeby.io/ kept saying “URL doesn't link to supported services”, when I try to get test ETH.

**Comment by sudhirnatarajan** [comment]
Same error
