### ISSUE TITLE
Create a tutorial based on the media player

### ISSUE THREAD

**Issue by ericxtang** [livepeer/docs#16]
We should create a tutorial based on the Livepeer [media player](https://github.com/livepeer/livepeerjs/tree/master/packages/player). 

Sections:
* Setting up a Livepeer node from scratch
* Setting up the media player
* Streaming a video into the Livepeer node, and watching the stream from the media player

**Comment by ericxtang** [comment]
duplicate to https://github.com/livepeer/docs/issues/16

**Comment by chrishobcroft** [comment]
I would collaborate with you on this with you.
