### ISSUE TITLE
Migrate existing docs

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/docs#260]

**Comment by adamsoffer** [comment]
## Guides

- [ ] Create a video asset (exists in livepeerjs)
- [ ] Create a livestream (exists in livepeerjs) 
- [ ] Playback a video (exists in old docs, has been updated) 
- [ ] Play a video from IPFS or Arweave (exists in livepeerjs) 
- [ ] Stream with Access Control (exists in livepeerjs) 
- [ ] Listen for webhooks (needs to be updated from old docs) 
- [ ] Multistream to multiple destinations (needs to be updated from old docs) 
- [ ] Get viewer engagement (exists in old docs, has been updated) 
- [ ] Monitor stream health (needs to be updated from old docs)
- [ ] Stream via OBS (needs to be updated from old docs)
- [ ] Stream via the browser (needs to be updated from old docs)

**Comment by 0xcadams** [comment]
I removed the "Stream via browser" because it references an SDK that hasn't been updated in a year
