### ISSUE TITLE
Playback URLs

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/docs#275]
Update playback URLs for assets and streams.
Not sure what the conclusion of this conversation is 
https://discord.com/channels/423160867534929930/1049464280111652996/1050101319295311892

In the current dashboard the playback URLs are:
Stream: https://livepeercdn.studio/hls/<playbackID>/index.m3u8
Assets: https://lp-playback.com/hls/<playbackID>/index.m3u8

In the docs:https://docs.livepeer.org/guides/developing/player
Stream:https://livepeercdn.com/hls/{PLAYBACK_ID}/index.m3u8
Asset: https://livepeercdn.com/asset/{PLAYBACK_ID}/video

**Comment by 0xcadams** [comment]
Fixed
