### ISSUE TITLE
Broken deployed contract addresses link

### ISSUE THREAD

**Issue by dob** [livepeer/docs#277]
Top google search result (and my bookmark) for our deployed contract addresses link is broken: https://docs.livepeer.org/protocol/reference/deployed

![Screen Shot 2022-12-20 at 9 22 05 AM](https://user-images.githubusercontent.com/10389/208689032-34cf2aa9-0023-4a1d-bcfd-fd3b274dca64.png)

cc @adamsoffer

**Comment by adamsoffer** [comment]
🙏 resolved in #278
