### ISSUE TITLE
Difference of session duration using GET stream sessions and LP portal

### ISSUE THREAD

**Issue by JesusGerardoAguiar** [livepeer/docs#300]
### Current/Expected Behavior

Hello!, I'm now experiencing a problem in which, for some reason, when I compute the duration of my stream using createdAt and lastSeen, I get a disparity in minutes with the sessions displayed on the Livepeer Portal.

![image](https://user-images.githubusercontent.com/42016025/211571793-e482342b-5df2-447a-9483-932676195905.png)
![image](https://user-images.githubusercontent.com/42016025/211571863-b4662a6c-3c67-4e4e-80df-795e24b8454c.png)

I'm not sure if I'm miscalculating the duration or if Livepeer is taking other parameters into account when determining the stream's session.

**Comment by Shih-Yu** [comment]
@JesusGerardoAguiar 
Sorry for the delay in the response, what you brought up is correct that the time recording sometimes does not line up. We are working on a fix for this but not sure when exactly at the moment.

**Comment by adamsoffer** [comment]
Hey @Shih-Yu - by any chance do you know if this has been addressed?

**Comment by Shih-Yu** [comment]
@adamsoffer I believe that the new recording pipeline that was just released should address this issue.

**Comment by adamsoffer** [comment]
Awesome!
