### ISSUE TITLE
[bug] Broken Link

### ISSUE THREAD

**Issue by sasicodes** [livepeer/docs#303]
### Current/Expected Behavior

Visit -> https://docs.livepeer.org/guides/developing/viewer-engagement#step-3-view-your-assets-viewership-metrics

https://docs.livepeer.org/guides/developing/view-asset

### Link to Docs Page (if applicable)

https://docs.livepeer.org/guides/developing/view-asset

**Comment by adamsoffer** [comment]
Fixed by https://github.com/livepeer/docs/commit/153dcd06cc98ba9d702047f0e0df2803635bca2d
