### ISSUE TITLE
[bug] Cannot switch language tabs

### ISSUE THREAD

**Issue by hansy** [livepeer/docs#318]
### Current/Expected Behavior

Unable to toggle to the React Native set of docs when clicking on the React Native tab. 

Browser: Firefox/Chrome
OS: Ubuntu 22

Also experiencing issue on mobile.

### Link to Docs Page (if applicable)

https://docs.livepeer.org/reference/livepeer-js/getting-started

**Comment by adamsoffer** [comment]
@0xcadams it appears like a regression caused all the tabs on the docs to stop working? Any idea?

**Comment by adamsoffer** [comment]
I just manually redeployed from the vercel dashboard and appears fixed now. Not sure what was causing that issue. Will monitor though.
