### ISSUE TITLE
[bug] Broken "create stream" link on the Streaming with OBS guide

### ISSUE THREAD

**Issue by hbizi** [livepeer/docs#330]
### Current/Expected Behavior

Visit
https://docs.livepeer.org/guides/developing/stream-via-obs

go to the Prepare the Environment section, click on "create a stream" and you'll be directed to a 404 page.

### Link to Docs Page (if applicable)

https://docs.livepeer.org/guides/developing/stream-via-obs

**Comment by adamsoffer** [comment]
Fixed by https://github.com/livepeer/docs/commit/13e94ca6068043cccc1f4c1e49296b11331d4c94
