### ISSUE TITLE
Developing on Livepeer - link for setting up development environment takes you to the same page

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/docs#35]
I'm looking at https://livepeer.readthedocs.io/en/latest/developers.html which comes from https://github.com/livepeer/docs/blob/master/docs/source/developers.rst

There's a bit which says:

> Setting up a development enviroment can be done by following `these instructions`_.

The link "these instructions" takes you to _the same page_ - i.e. if someone wanted to set up a development environment, they would not get to it.

Perhaps it would encourage more developers to "develop on Livepeer" if these instructions existed?

**Comment by yondonfu** [comment]
Closing since this content is no longer included in livepeer.org/docs, the new canonical docs site.
