### ISSUE TITLE
[bug] "Request Docs Coverage" link broken when submitting issue

### ISSUE THREAD

**Issue by hansy** [livepeer/docs#378]
### Current/Expected Behavior

The link for "Request Docs Coverage" leads to a 404 on Github.

<img width="1194" alt="Screenshot 2023-05-05 at 9 45 56 AM" src="https://user-images.githubusercontent.com/775807/236491127-0e2c9a50-fa83-4c0e-b8b2-85c363d6bc70.png">

### Link to Docs Page (if applicable)

https://github.com/livepeer/docs/discussions/new?category=ideas

**Comment by adamsoffer** [comment]
Thanks @hansy. I fixed the link so it points to the developer forum in discord.
