### ISSUE TITLE
[bug] Broken link

### ISSUE THREAD

**Issue by amochuko** [livepeer/docs#426]
### Current/Expected Behavior

This is from the [mint-a-video-nft](https://docs.livepeer.org/guides/developing/mint-a-video-nft) page, which provides the [Create Asset](https://docs.livepeer.org/examples/react/view-asset) example page link. 

But upon accessing, the page results in a:  404 - This page could not be found

### Link to Docs Page (if applicable)

https://docs.livepeer.org/examples/react/view-asset

**Comment by suhailkakar** [comment]
Thanks! the page is now back: https://docs.livepeer.org/developers/guides/mint-video-nft
