### ISSUE TITLE
signAccessJwt import

### ISSUE THREAD

**Issue by wes337** [livepeer/docs#483]
https://github.com/livepeer/docs/blob/ce7ce0bc5a51e6774cd809661d572c1d1a0eb64a/developers/guides/access-control-jwt.mdx#L123

After updating `@livepeer/core-web` to > 3.0.0, the `signAccessJwt` is no longer imported as shown in the docs

Current:
```
import { signAccessJwt } from "@livepeer/crypto";
```

New:
```
import { signAccessJwt } from "@livepeer/core/crypto";
```

**Comment by suhailkakar** [comment]
This has been fixed, thanks!
