### ISSUE TITLE
Little/unclear/no documentation on `Assets uploading API`

### ISSUE THREAD

**Issue by bitspresso** [livepeer/docs#523]
## Background
Hey, as a newcomer to Livepeer, first of all I directed myself to documentation. As available SDKs do not meet my requirements (no support for the stack), the only reference would be API section.
## Details
Starting from `Asset-`>`Upload an asset`, I've been confused. Yes, I receive a JSON - so, what's next? What is the `url` property and how am I supposed to deal with `tusEndpoint`? What about `encryptionKey`: is it arbitrary or should I retrieve a specific one?
After digging a while, I found teeny-tiny block of information regarding direct upload [here](https://github.com/livepeer/livepeer-js/blob/main/docs/sdks/asset/README.md#create), which, surprisingly, was misleading (at least for my case).

*Still having a bit of patience, so I'll stick with a messy workaround.*

**Comment by 0xcadams** [comment]
Internal Linear issue here: https://linear.app/livepeer/issue/ENG-1987/littleunclearno-documentation-on-assets-uploading-api

**Comment by 0xcadams** [comment]
Thanks for reporting @bitspresso. We have this on our backlog now and will get some fixes to address this.
