### ISSUE TITLE
Mention blockPollingInterval flag in quickstart

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/docs#63]
The default `blockPollingInterval` exceeds Infura's 100k requests/day. Since most orchestrators rely on Infura's free tier, we should recommend orchestrators set the `blockPollingInterval` to 12 seconds (`-blockPollingInterval 12`) to avoid exceeding Infura's request per day limit.

**Comment by yondonfu** [comment]
Closing since a single node should stay within Infura's free tier now. Though this flag could always be mentioned in references (right now the CLI flag reference just points to the code itself).
